#!/bin/sh

dir=$SNAP/ts3
data=$SNAP_USER_DATA/client
mkdir -p $data
license=$data/.license_seen

if ! [ -f $license ]; then
  . $SNAP/lib/license
  askforlicense
  touch $license
fi

export HOME=$data

#export KDEDIRS=
#export KDEDIR=
#export QTDIR=.
#export QT_PLUGIN_PATH=.
#export LD_LIBRARY_PATH="$dir:.:$LD_LIBRARY_PATH"

#cd $dir

#if [ -e $dir/ts3client_linux_x86 ]; then
#	$dir/ts3client_linux_x86 $@
#else
#	$dir/ts3client_linux_amd64 $@
#fi

cd $dir

export KDEDIRS=
export KDEDIR=
export QTDIR=.
export QT_PLUGIN_PATH=.
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:."

if [ -e ts3client_linux_x86 ]; then
	bash $SNAP/bin/desktop-launch ./ts3client_linux_x86 $@
else
	bash $SNAP/bin/desktop-launch ./ts3client_linux_amd64 $@
fi
