#!/bin/sh

dir=$SNAP/bin/client
data=$SNAP_USER_DATA/client
mkdir -p $data
license=$data/LICENSE.ok

if ! [ -f $license ]; then
  eval "$(cat $SNAP/lib/license)"
  askforlicense
  touch $license
fi

export HOME=$data

export KDEDIRS=
export KDEDIR=
export QTDIR=.
export QT_PLUGIN_PATH=.
export LD_LIBRARY_PATH="$dir:.:$LD_LIBRARY_PATH"

cd $dir

if [ -e $dir/ts3client_linux_x86 ]; then
	$dir/ts3client_linux_x86 $@
else
	$dir/ts3client_linux_amd64 $@
fi
