name: teamspeak3-server
version: 0.0.1
summary: Teamspeak3 Server
description: Teamspeak3 Server and TSDNS
confinement: strict

apps:
  teamspeak3-server:
    command: bash $SNAP/bin/teamspeak
#    daemon: simple
    plugs:
      - network-bind
      - network
  tsdns:
    command: bash $SNAP/bin/tsdns
#    daemon: simple
    plugs:
      - network-bind
      - network
parts:
#  sqlite3:
#      plugin: nil
#      stage-packages:
#          - sqlite3
#      snap:
#          - -usr/bin/sqlite3
  glue:
    plugin: copy
#    after:
#        - sqlite3
    files:
      bin: bin
      ts3server: bin/server
      daemon: bin/teamspeak
      tsdns: bin/tsdns
